import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import type { Payment } from '@/data/mockData';
import { useAuth } from '@/contexts/AuthContext';
import { useProfile } from '@/hooks/queries/useProfile';
import { getLocalTodayDate } from '@/lib/dateUtils';
import { syncAfterPaymentMutation } from '@/lib/querySync';
import type { Tables } from '@/integrations/supabase/types';
import { isCancelledPayment } from '@/lib/financialContracts';

type PaymentRowWithStudent = Tables<'payments'> & {
    students?: {
        active: boolean | null;
    } | null;
};

/**
 * Hook centralizado para gerenciamento de pagamentos.
 * 
 * CORREÇÃO CRÍTICA: Agora gera automaticamente os pagamentos do mês corrente
 * na primeira carga, independentemente de qual página o usuário abra primeiro.
 * Isso resolve a discrepância entre Dashboard (que mostrava R$ 0) e PaymentsPage.
 */
export function usePayments(options: { enabled?: boolean } = {}) {
    const queryClient = useQueryClient();
    const { user } = useAuth();
    const { profile, loadingProfile } = useProfile();
    const autoGeneratedKeys = useRef<Set<string>>(new Set());
    const paymentsEnabled = options.enabled ?? true;

    const tenantId = profile?.owner_user_id || user?.id;

    const { data: payments = [], isLoading: loadingPayments } = useQuery({
        queryKey: ['payments', tenantId, profile?.business_type],
        queryFn: async () => {
            if (!tenantId) return [];
            const businessType = profile?.business_type || 'sport_school';
            const { data, error } = await supabase
                .from('payments')
                // Inclui o status do aluno para filtrar pagamentos pendentes de alunos inativos
                .select('*, students(active)')
                .eq('user_id', tenantId)
                .eq('business_type', businessType)
                .order('due_date', { ascending: true });
            if (error) throw error;

            const rows = (data || []) as PaymentRowWithStudent[];

            return rows
                .filter((p) => {
                    if (Number(p.full_price) === -1) return true;

                    const student = p.students;
                    if (!p.paid && student && student.active === false) return false;

                    return true;
                })
                .map((p) => ({
                    id: p.id,
                    userId: p.user_id,
                    studentId: p.student_id,
                    planId: p.plan_id,
                    amount: Number(p.amount),
                    dueDate: p.due_date,
                    paid: p.paid,
                    paidAt: p.paid_at || undefined,
                    monthRef: p.month_ref,
                    createdAt: p.created_at,
                    isProrata: p.is_prorata || false,
                    fullPrice: p.full_price !== null ? Number(p.full_price) : undefined,
                    paidAmount: p.paid && (!p.paid_amount || Number(p.paid_amount) === 0)
                        ? Number(p.amount)
                        : (p.paid_amount !== undefined && p.paid_amount !== null ? Number(p.paid_amount) : 0),
                })) as Payment[];
        },
        enabled: paymentsEnabled && !!tenantId && !loadingProfile,
    });

    const activePayments = useMemo(() => {
        return payments.filter((payment) => !isCancelledPayment(payment));
    }, [payments]);

    const cancelledPayments = useMemo(() => {
        return payments.filter((payment) => isCancelledPayment(payment));
    }, [payments]);

    // Auto-generate payments for the CURRENT month once per session.
    // This ensures Dashboard, Reports, and any page see correct data
    // even if the user never visits PaymentsPage first.
    useEffect(() => {
        if (!paymentsEnabled || !tenantId || loadingProfile || loadingPayments) return;

        // Obtém o mês atual (YYYY-MM) no horário local, não UTC, para evitar erros de fuso horário
        const currentMonthRef = getLocalTodayDate().slice(0, 7);
        const businessType = profile?.business_type || 'sport_school';
        const generationKey = `${businessType}:${currentMonthRef}`;

        if (autoGeneratedKeys.current.has(generationKey)) return;

        const hasCurrentMonth = activePayments.some(p => p.monthRef === currentMonthRef);

        if (!hasCurrentMonth) {
            autoGeneratedKeys.current.add(generationKey);
            supabase.rpc('generate_monthly_payments', {
                p_month_ref: currentMonthRef,
            }).then(({ data, error }) => {
                if (!error && data && (data as number) > 0) {
                    syncAfterPaymentMutation(queryClient);
                }
            });
        } else {
            autoGeneratedKeys.current.add(generationKey);
        }
    }, [paymentsEnabled, tenantId, loadingProfile, loadingPayments, activePayments, queryClient, profile?.business_type]);

    const markAsPaidMutation = useMutation({
        mutationFn: async ({ paymentId, paidAmount }: { paymentId: string; paidAmount?: number }) => {
            const { error } = await supabase.rpc('receive_payment_atomic', {
                p_payment_id: paymentId,
                p_paid_amount: paidAmount ?? null,
            });
            if (error) throw error;
        },
        onSuccess: () => {
            syncAfterPaymentMutation(queryClient);
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao marcar pagamento', description: error.message, variant: 'destructive' });
        },
    });

    const markAsUnpaidMutation = useMutation({
        mutationFn: async (paymentId: string) => {
            const { error } = await supabase.rpc('reopen_payment_atomic', {
                p_payment_id: paymentId,
            });
            if (error) throw error;
        },
        onSuccess: () => {
            syncAfterPaymentMutation(queryClient);
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao desmarcar pagamento', description: error.message, variant: 'destructive' });
        },
    });

    const deletePaymentMutation = useMutation({
        mutationFn: async (paymentId: string) => {
            // Cancela a cobranca via RPC para impedir regeneracao automatica.
            const { error } = await supabase.rpc('cancel_payment_atomic', {
                p_payment_id: paymentId,
            });
            if (error) throw error;
        },
        onSuccess: () => {
            syncAfterPaymentMutation(queryClient);
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao excluir pagamento', description: error.message, variant: 'destructive' });
        },
    });

    const restorePaymentMutation = useMutation({
        mutationFn: async (paymentId: string) => {
            const { error } = await supabase.rpc('restore_cancelled_payment_atomic', {
                p_payment_id: paymentId,
            });
            if (error) throw error;
        },
        onSuccess: () => {
            syncAfterPaymentMutation(queryClient);
            toast({ title: 'Cobrança restaurada', description: 'A cobrança voltou para a lista de pagamentos pendentes.' });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao restaurar cobrança', description: error.message, variant: 'destructive' });
        },
    });

    /**
     * Gera os pagamentos mensais para um mês específico.
     * Usado pela PaymentsPage quando o usuário navega para meses diferentes do atual.
     */
    const generateMonthlyPaymentsMutation = useMutation({
        mutationFn: async (monthRef: string) => {
            if (!tenantId) throw new Error('Usuário não autenticado');

            const { data, error } = await supabase.rpc('generate_monthly_payments', {
                p_month_ref: monthRef
            });

            if (error) throw error;
            return { count: data as number };
        },
        onSuccess: (data) => {
            syncAfterPaymentMutation(queryClient);
            if (data?.count && data.count > 0) {
                toast({
                    title: 'Pagamentos gerados',
                    description: `${data.count} pagamento(s) gerado(s) com sucesso.`,
                });
            }
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao gerar pagamentos', description: error.message, variant: 'destructive' });
        },
    });

    /**
     * Sincroniza pagamentos não pagos de um aluno específico após troca de plano ou vencimento.
     */
    const syncStudentPaymentsMutation = useMutation({
        mutationFn: async (params: { studentId: string, planChanged: boolean, newPlanId?: string | null, newDueDay?: number | null }) => {
            if (!tenantId) throw new Error('Usuário não autenticado');
            
            const { error } = await supabase.rpc('sync_student_unpaid_payments', {
                p_student_id: params.studentId,
                p_plan_changed: params.planChanged,
                p_new_plan_id: params.newPlanId || null,
                p_new_due_day: params.newDueDay || null
            });

            if (error) throw error;
        },
        onSuccess: () => {
            syncAfterPaymentMutation(queryClient);
        }
    });

    const markBatchAsPaidMutation = useMutation({
        mutationFn: async (paymentIds: string[]) => {
            const { error } = await supabase.rpc('receive_payments_batch_atomic', {
                p_payment_ids: paymentIds,
            });
            if (error) throw error;
        },
        onSuccess: () => {
            syncAfterPaymentMutation(queryClient);
            toast({ title: 'Pagamentos em lote', description: 'Pagamentos marcados como pagos com sucesso.' });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro em lote', description: error.message, variant: 'destructive' });
        }
    });

    const markBatchAsUnpaidMutation = useMutation({
        mutationFn: async (paymentIds: string[]) => {
            const { error } = await supabase.rpc('reopen_payments_batch_atomic', {
                p_payment_ids: paymentIds,
            });
            if (error) throw error;
        },
        onSuccess: () => {
            syncAfterPaymentMutation(queryClient);
            toast({ title: 'Pagamentos em lote', description: 'Pagamentos desmarcados com sucesso.' });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro em lote', description: error.message, variant: 'destructive' });
        }
    });

    return {
        payments: activePayments,
        cancelledPayments,
        loadingPayments,
        markAsPaid: async (id: string, paidAmount?: number) => markAsPaidMutation.mutateAsync({ paymentId: id, paidAmount }),
        markAsUnpaid: async (id: string) => markAsUnpaidMutation.mutateAsync(id),
        markBatchAsPaid: async (ids: string[]) => markBatchAsPaidMutation.mutateAsync(ids),
        markBatchAsUnpaid: async (ids: string[]) => markBatchAsUnpaidMutation.mutateAsync(ids),
        deletePayment: async (id: string) => deletePaymentMutation.mutateAsync(id),
        restorePayment: async (id: string) => restorePaymentMutation.mutateAsync(id),
        generateMonthlyPayments: async (monthRef: string) =>
            generateMonthlyPaymentsMutation.mutateAsync(monthRef),
        syncStudentPayments: async (params: { studentId: string, planChanged: boolean, newPlanId?: string | null, newDueDay?: number | null }) =>
            syncStudentPaymentsMutation.mutateAsync(params),
    };
}
