import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useEffect, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import type { Payment } from '@/data/mockData';
import { useAuth } from '@/contexts/AuthContext';
import { useProfile } from '@/hooks/queries/useProfile';
import { getLocalTodayDate } from '@/lib/dateUtils';

/**
 * Hook centralizado para gerenciamento de pagamentos.
 * 
 * CORREÇÃO CRÍTICA: Agora gera automaticamente os pagamentos do mês corrente
 * na primeira carga, independentemente de qual página o usuário abra primeiro.
 * Isso resolve a discrepância entre Dashboard (que mostrava R$ 0) e PaymentsPage.
 */
export function usePayments() {
    const queryClient = useQueryClient();
    const { user } = useAuth();
    const { profile } = useProfile();
    const autoGenerated = useRef(false);

    const { data: payments = [], isLoading: loadingPayments } = useQuery({
        queryKey: ['payments', user?.id, profile?.business_type],
        queryFn: async () => {
            if (!user) return [];
            const businessType = profile?.business_type || 'sport_school';
            const { data, error } = await supabase
                .from('payments')
                // Inclui o status do aluno para filtrar pagamentos pendentes de alunos inativos
                .select('*, students(active)')
                .eq('user_id', user.id)
                .eq('business_type', businessType)
                .order('due_date', { ascending: true });
            if (error) throw error;

            return data
                .filter((p: Record<string, any>) => {
                    // 1. Oculta pagamentos apagados via soft-delete
                    if (Number(p.full_price) === -1) return false;
                    // 2. Correção retroativa: oculta pagamentos PENDENTES de alunos INATIVOS
                    //    (cobre alunos desativados antes desta versão do sistema)
                    const student = p.students as Record<string, any> | undefined;
                    if (!p.paid && student && student.active === false) return false;
                    return true;
                })
                .map((p: Record<string, any>) => ({
                id: p.id,
                userId: p.user_id,
                studentId: p.student_id,
                planId: p.plan_id,
                amount: Number(p.amount),
                dueDate: p.due_date,
                paid: p.paid,
                paidAt: p.paid_at,
                monthRef: p.month_ref,
                createdAt: p.created_at,
                isProrata: p.is_prorata || false,
                fullPrice: p.full_price ? Number(p.full_price) : undefined,
                paidAmount: p.paid && (!p.paid_amount || Number(p.paid_amount) === 0) 
                    ? Number(p.amount) 
                    : (p.paid_amount !== undefined && p.paid_amount !== null ? Number(p.paid_amount) : 0),
            })) as Payment[];
        },
        enabled: !!user,
    });

    // Auto-generate payments for the CURRENT month once per session.
    // This ensures Dashboard, Reports, and any page see correct data
    // even if the user never visits PaymentsPage first.
    useEffect(() => {
        if (!user || loadingPayments || autoGenerated.current) return;

        // Obtém o mês atual (YYYY-MM) no horário local, não UTC, para evitar erros de fuso horário
        const currentMonthRef = getLocalTodayDate().slice(0, 7);
        const hasCurrentMonth = payments.some(p => p.monthRef === currentMonthRef);

        if (!hasCurrentMonth) {
            autoGenerated.current = true;
            const businessType = profile?.business_type || 'sport_school';
            supabase.rpc('generate_monthly_payments', {
                p_month_ref: currentMonthRef,
            }).then(({ data, error }) => {
                if (!error && data && (data as number) > 0) {
                    queryClient.invalidateQueries({ queryKey: ['payments'] });
                }
            });
        } else {
            autoGenerated.current = true;
        }
    }, [user, loadingPayments, payments, queryClient, profile?.business_type]);

    const markAsPaidMutation = useMutation({
        mutationFn: async ({ paymentId, paidAmount }: { paymentId: string; paidAmount?: number }) => {
            let finalPaidAmount = paidAmount;
            let isFullyPaid = true;

            const { data: payRow, error: fetchErr } = await supabase
                .from('payments')
                .select('amount')
                .eq('id', paymentId)
                .single();
                
            if (fetchErr) throw fetchErr;

            if (finalPaidAmount === undefined) {
                finalPaidAmount = Number(payRow.amount);
            } else if (finalPaidAmount < Number(payRow.amount)) {
                isFullyPaid = false;
            }

            const { error } = await supabase
                .from('payments')
                .update({ 
                    paid: isFullyPaid, 
                    paid_amount: finalPaidAmount, 
                    paid_at: new Date().toISOString() 
                })
                .eq('id', paymentId);
            if (error) throw error;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao marcar pagamento', description: error.message, variant: 'destructive' });
        },
    });

    const markAsUnpaidMutation = useMutation({
        mutationFn: async (paymentId: string) => {
            const { error } = await supabase
                .from('payments')
                .update({ paid: false, paid_at: null, paid_amount: 0 })
                .eq('id', paymentId);
            if (error) throw error;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao desmarcar pagamento', description: error.message, variant: 'destructive' });
        },
    });

    const deletePaymentMutation = useMutation({
        mutationFn: async (paymentId: string) => {
            // Em vez de deletar a linha, fazemos um "soft delete" marcando full_price = -1 e valor = 0.
            // Isso engana o RPC do banco (ele vê que a linha existe e não a recria), 
            // mas o front-end filtra essa linha (ela não aparece mais na UI nem soma nos cálculos).
            const { error } = await supabase.from('payments').update({
                amount: 0,
                paid_amount: 0,
                paid: true,
                full_price: -1
            }).eq('id', paymentId);
            if (error) throw error;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao excluir pagamento', description: error.message, variant: 'destructive' });
        },
    });

    /**
     * Gera os pagamentos mensais para um mês específico.
     * Usado pela PaymentsPage quando o usuário navega para meses diferentes do atual.
     */
    const generateMonthlyPaymentsMutation = useMutation({
        mutationFn: async (monthRef: string) => {
            if (!user) throw new Error('Usuário não autenticado');

            const businessType = profile?.business_type || 'sport_school';
            const { data, error } = await supabase.rpc('generate_monthly_payments', {
                p_month_ref: monthRef
            });

            if (error) throw error;
            return { count: data as number };
        },
        onSuccess: (data) => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
            if (data?.count && data.count > 0) {
                toast({
                    title: 'Pagamentos gerados',
                    description: `${data.count} pagamento(s) gerado(s) com sucesso.`,
                });
            }
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao gerar pagamentos', description: error.message, variant: 'destructive' });
        },
    });

    /**
     * Sincroniza pagamentos não pagos de um aluno específico após troca de plano ou vencimento.
     */
    const syncStudentPaymentsMutation = useMutation({
        mutationFn: async (params: { studentId: string, planChanged: boolean, newPlanId?: string | null, newDueDay?: number | null }) => {
            if (!user) throw new Error('Usuário não autenticado');
            
            const { error } = await supabase.rpc('sync_student_unpaid_payments', {
                p_student_id: params.studentId,
                p_plan_changed: params.planChanged,
                p_new_plan_id: params.newPlanId || null,
                p_new_due_day: params.newDueDay || null
            });

            if (error) throw error;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
        }
    });

    const markBatchAsPaidMutation = useMutation({
        mutationFn: async (paymentIds: string[]) => {
            await Promise.all(paymentIds.map(async (id) => {
                const { data: payRow } = await supabase.from('payments').select('amount').eq('id', id).single();
                if (payRow) {
                    await supabase.from('payments').update({
                        paid: true,
                        paid_amount: payRow.amount,
                        paid_at: new Date().toISOString()
                    }).eq('id', id);
                }
            }));
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
            toast({ title: 'Pagamentos em lote', description: 'Pagamentos marcados como pagos com sucesso.' });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro em lote', description: error.message, variant: 'destructive' });
        }
    });

    const markBatchAsUnpaidMutation = useMutation({
        mutationFn: async (paymentIds: string[]) => {
            await Promise.all(paymentIds.map(async (id) => {
                await supabase.from('payments').update({
                    paid: false,
                    paid_amount: 0,
                    paid_at: null
                }).eq('id', id);
            }));
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
            toast({ title: 'Pagamentos em lote', description: 'Pagamentos desmarcados com sucesso.' });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro em lote', description: error.message, variant: 'destructive' });
        }
    });

    return {
        payments,
        loadingPayments,
        markAsPaid: async (id: string, paidAmount?: number) => markAsPaidMutation.mutateAsync({ paymentId: id, paidAmount }),
        markAsUnpaid: async (id: string) => markAsUnpaidMutation.mutateAsync(id),
        markBatchAsPaid: async (ids: string[]) => markBatchAsPaidMutation.mutateAsync(ids),
        markBatchAsUnpaid: async (ids: string[]) => markBatchAsUnpaidMutation.mutateAsync(ids),
        deletePayment: async (id: string) => deletePaymentMutation.mutateAsync(id),
        generateMonthlyPayments: async (monthRef: string) =>
            generateMonthlyPaymentsMutation.mutateAsync(monthRef),
        syncStudentPayments: async (params: { studentId: string, planChanged: boolean, newPlanId?: string | null, newDueDay?: number | null }) =>
            syncStudentPaymentsMutation.mutateAsync(params),
    };
}
