import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useEffect, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import type { Payment } from '@/data/mockData';
import { useAuth } from '@/contexts/AuthContext';

/**
 * Hook centralizado para gerenciamento de pagamentos.
 * 
 * CORREÇÃO CRÍTICA: Agora gera automaticamente os pagamentos do mês corrente
 * na primeira carga, independentemente de qual página o usuário abra primeiro.
 * Isso resolve a discrepância entre Dashboard (que mostrava R$ 0) e PaymentsPage.
 */
export function usePayments() {
    const queryClient = useQueryClient();
    const { user } = useAuth();
    const autoGenerated = useRef(false);

    const { data: payments = [], isLoading: loadingPayments } = useQuery({
        queryKey: ['payments', user?.id],
        queryFn: async () => {
            if (!user) return [];
            const { data, error } = await supabase
                .from('payments')
                .select('*')
                .order('due_date', { ascending: true });
            if (error) throw error;
            return data.map((p: any) => ({
                id: p.id,
                userId: p.user_id,
                studentId: p.student_id,
                planId: p.plan_id,
                amount: Number(p.amount),
                dueDate: p.due_date,
                paid: p.paid,
                paidAt: p.paid_at,
                monthRef: p.month_ref,
                createdAt: p.created_at,
                isProrata: p.is_prorata || false,
                fullPrice: p.full_price ? Number(p.full_price) : undefined,
            })) as Payment[];
        },
        enabled: !!user,
    });

    // Auto-generate payments for the CURRENT month once per session.
    // This ensures Dashboard, Reports, and any page see correct data
    // even if the user never visits PaymentsPage first.
    useEffect(() => {
        if (!user || loadingPayments || autoGenerated.current) return;

        // Obtém o mês atual (YYYY-MM) no horário local, não UTC, para evitar erros de fuso horário
        const currentMonthRef = new Date().toLocaleDateString('en-CA').slice(0, 7);
        const hasCurrentMonth = payments.some(p => p.monthRef === currentMonthRef);

        if (!hasCurrentMonth) {
            autoGenerated.current = true;
            supabase.rpc('generate_monthly_payments', {
                p_month_ref: currentMonthRef,
            }).then(({ data, error }) => {
                if (!error && data && (data as number) > 0) {
                    queryClient.invalidateQueries({ queryKey: ['payments'] });
                }
            });
        } else {
            autoGenerated.current = true;
        }
    }, [user, loadingPayments, payments, queryClient]);

    const markAsPaidMutation = useMutation({
        mutationFn: async (paymentId: string) => {
            const { error } = await supabase
                .from('payments')
                .update({ paid: true, paid_at: new Date().toISOString() })
                .eq('id', paymentId);
            if (error) throw error;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao marcar pagamento', description: error.message, variant: 'destructive' });
        },
    });

    const markAsUnpaidMutation = useMutation({
        mutationFn: async (paymentId: string) => {
            const { error } = await supabase
                .from('payments')
                .update({ paid: false, paid_at: null })
                .eq('id', paymentId);
            if (error) throw error;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao desmarcar pagamento', description: error.message, variant: 'destructive' });
        },
    });

    const deletePaymentMutation = useMutation({
        mutationFn: async (paymentId: string) => {
            const { error } = await supabase.from('payments').delete().eq('id', paymentId);
            if (error) throw error;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao excluir pagamento', description: error.message, variant: 'destructive' });
        },
    });

    /**
     * Gera os pagamentos mensais para um mês específico.
     * Usado pela PaymentsPage quando o usuário navega para meses diferentes do atual.
     */
    const generateMonthlyPaymentsMutation = useMutation({
        mutationFn: async (monthRef: string) => {
            if (!user) throw new Error('Usuário não autenticado');

            const { data, error } = await supabase.rpc('generate_monthly_payments', {
                p_month_ref: monthRef
            });

            if (error) throw error;
            return { count: data as number };
        },
        onSuccess: (data) => {
            queryClient.invalidateQueries({ queryKey: ['payments'] });
            if (data?.count && data.count > 0) {
                toast({
                    title: 'Pagamentos gerados',
                    description: `${data.count} pagamento(s) gerado(s) com sucesso.`,
                });
            }
        },
        onError: (error: Error) => {
            toast({ title: 'Erro ao gerar pagamentos', description: error.message, variant: 'destructive' });
        },
    });

    return {
        payments,
        loadingPayments,
        markAsPaid: async (id: string) => markAsPaidMutation.mutateAsync(id),
        markAsUnpaid: async (id: string) => markAsUnpaidMutation.mutateAsync(id),
        deletePayment: async (id: string) => deletePaymentMutation.mutateAsync(id),
        generateMonthlyPayments: async (monthRef: string) =>
            generateMonthlyPaymentsMutation.mutateAsync(monthRef),
    };
}
