// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crwaerhlrzqzxqaijkqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyd2FlcmhscnpxenhxYWlqa3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0Mjc3ODIsImV4cCI6MjA4NzAwMzc4Mn0.xScqfkFgu2Uy9YIRAWIyZks87Ga8Th2P_ON17C2OB88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});